### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by kevinchevallier** [hagata/unwrap-project#8]
Hey Genki,
what version of node should we use? I've tried with 0.12.7 and 4.1.1 and got an error at installation:

```
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/unwrap-storage/'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at Object.module.exports.createPersistFile (/usr/local/lib/node_modules/unwrap-project/utils/utils:22:8)
...
```

Would that be related to the unwrap-project?
Thanks

**Comment by hagata** [comment]
@kevinchevallier It looks like a permission issue creating directories rather than an issue with node. 

are you also seeing:

```
npm ERR! Please try running this command again as root/Administrator.
```

**Comment by hagata** [comment]
Fixed with running with `sudo` and/ or changing permissions to `unwrap-storage` directory. added to known issues in the readme.

``` bash
#install unwrap
sudo npm install -g unwrap-project

#init unwrap and setup unwrap-storage
sudo unwrap

#set permissions on path to /unwrap-storage/
sudo chmod -R 0777 /usr/lib/node_modules/unwrap-storage

```
